galaxy: Resultado_galaxia_momento_0.pdf

Resultado_galaxia_momento_0.pdf: plots.py resultado_galaxia_0.txt
	python plots.py

resultado_galaxia_0.txt: evolve.x condiciones_iniciales.txt
	./evolve.x condiciones_iniciales.txt 5 5 

evolve.x: evolve.c
	cc evolve.c -lm -o evolve.x

condiciones_iniciales.txt: condiciones_galaxia_0.txt 
	cat condiciones_galaxia_0.txt > condiciones_iniciales.txt

condiciones_galaxia_0.txt: IC.x
	./IC.x 0 0 0 0 0 0 100000 20 1000

IC.x: IC.c
	cc IC.c -lm -o IC.x


clean: 
	rm *.txt *.pdf 

cleanx: 
	rm *.x	